### ISSUE TITLE
Initialize owf-common library

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-dev-ng#3]
Need to initialize the `owf-common` library.  Technical considerations are as follows:

1. Follow the folder structure and naming conventions in the README.
2. Copy Java-ported code from InfoMapper.  Change paths to lowercase and leave classes MixedCase, for example `util/time/DateTime.ts`.
3. Implement `tsconfig.json`, etc. to allow imports to be used in general way.

**Comment by Nightsphere** [comment]
I believe this issue has been fulfilled. The common library has been created and used in the InfoMapper as a Github Package using npm to publish. Imports have been created in such a way that they can be as granular as needed. Any other updates to the library can be made into their own issues in the future. Closing this issue.
