### ISSUE TITLE
Dashboard to dashboard routing does not work

### ISSUE THREAD

**Issue by Nightsphere** [OpenWaterFoundation/owf-app-dev-ng#39]
Currently, there is no use of the built-in Angular paramMap observable for updating a dashboard by going from dashboard menu to dashboard menu. This should be fairly simple, since it's been done in the past.

**Comment by smalers** [comment]
I have seen problems where if I use a dashboard and then switch to another URL the app shows a white screen.  If that is what this issue is then it needs to be fixed ASAP.
