### ISSUE TITLE
Implement general WindowManager and dialog classes

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-dev-ng#4]
The application common code should include `WindowManager` class implemented in a way that any application can use.  The general dialog code will also need to be implemented to be compatible and allow other libraries to use, for example `owf-showdown`.

**Comment by Nightsphere** [comment]
This has been completed and has been tested for months with no issues. The `WindowManager` is currently being used in both the InfoMapper and SNODAS applications. Closing this issue.
