### ISSUE TITLE
Implement owf-showdown library

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-dev-ng#6]
**Josh should take the lead on this and leverage Sofia's work and help.**

Need to implement the `owf-showdown` library to enable popup information dialogs.  Technical considerations include:

1. Where appropriate, the library should depend on `owf-common`, for example if there is general dialog code.  This will be a good opportunity to demonstrate how one library can depend on another.
2. The library will depend on the showdown angular `npm` package, which will install in `node_modules`, right?
3. Copy appropriate code from the demo application, app1, and/or InfoMapper.
4. Make sure that the library can be deployed for other applications like InfoMapper.
5. Make sure that there is a method can be provided with a path to files consistent with what InfoMapper needs.  For example, code should take a full/absolute path and require path expansion before calling the showdown code?  That way the code is more stand-alone.

**Comment by Nightsphere** [comment]
It has been decided that the previously separate libraries will now all be used in the Common library. Closing this issue.
