### ISSUE TITLE
Map - does not open unless page is refreshed

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-dev-ng#61]
Both in the development environment and production Poudre Basin Information, I see the following exception on many maps.  Doing a soft or hard refresh usually fixes.  Is it a startup error where an event gets triggered before something is initialized?  In Java code I sometimes have to swallow events that get generated in one component before the UI is fully initialized.  The critical thing is to make sure that the components do initialize and then await user input.

![image](https://user-images.githubusercontent.com/6448274/183133537-31d1e8f8-a2b9-4525-b28e-94abc1e43645.png)

**Comment by Nightsphere** [comment]
There are two hypotheses for why this was error was occurring:

1. Pointing and using the larger datasets has somehow slowed the application down enough to throw the error.
2. Adding the `<ngIf="">` Angular directive to the map component template file has introduced a timing bug similarly to 1.

An update to the code will wait up to 10 seconds until the Map container is created on the DOM, and then create the Leaflet map by using the Map container's id. I will close this for now, but will possibly revisit it later.
