### ISSUE TITLE
Implement owf-plotly library

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-dev-ng#7]
**Josh should take the lead on this and leverage Sofia's work and help.**

Need to implement the `owf-plotly` library to enable popup time series graph dialogs.  Technical considerations include:

1. Where appropriate, the library should depend on `owf-common`, for example for time series code.  This will be a good opportunity to demonstrate how one library can depend on another.
2. The library will depend on the plotly angular `npm` package, which will install in `node_modules`, right?
3. Copy appropriate code from the demo application, app1, and/or InfoMapper.
4. Make sure that the library can be deployed for other applications like InfoMapper.
5. Handle relative/absolute path expansion.  For example, code should take a full/absolute path and require path expansion before calling the showdown code?  That way the code is more stand-alone.
6. Also will need to implement table viewing.  Is that part of core if Material table, or depends on another library like `owf-clusterize`?  Maybe it makes sense that `owf-common` provide some basic/default UI visualizations that can be used or overloaded with specific library.

**Comment by Nightsphere** [comment]
It has been decided that the previously separate libraries will now all be used in the Common library. Closing this issue.
